name: Update feed
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Update feed
        env:
          A72_URL: ${{ secrets.A72_URL }}
        run: mkdir output && ruby main.rb > output/district_10.json
      - name: Deploy feed
        uses: s0/git-publish-subdir-action@61eb9e6420447e7cbf010f7cce37103665c46bfa # develop as of 2024-10-13
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: output
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEAR_GLOBS_FILE: clear-globs
          SKIP_EMPTY_COMMITS: true
