name: Update feed
on:
  workflow_dispatch:
  schedule:
    - cron: '3/15 * * * *'

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Update feed
        env:
          PS_CSO_URL: ${{ secrets.PS_CSO_URL }}
        run: mkdir output && ruby main.rb > output/district_10.json
      - name: Deploy feed
        uses: s0/git-publish-subdir-action@92faf786f11dfa44fc366ac3eb274d193ca1af7e # develop as of 2024-02-15
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: output
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEAR_GLOBS_FILE: clear-globs
          SKIP_EMPTY_COMMITS: true
